//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongKhamNhaKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public string AppointmentId { get; set; }
        public string nameAppointment { get; set; }
        public System.DateTime scheduleDate { get; set; }
        public System.TimeSpan timeBegin { get; set; }
        public System.TimeSpan timeEnd { get; set; }
        public string note { get; set; }
        public string PatientId { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
