//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongKhamNhaKhoa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DentalClinic_DatabaseEntities : DbContext
    {
        public DentalClinic_DatabaseEntities()
            : base("name=DentalClinic_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AccountPermision> AccountPermisions { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<DetailPermision> DetailPermisions { get; set; }
        public virtual DbSet<DrugSupplier> DrugSuppliers { get; set; }
        public virtual DbSet<Medicine> Medicines { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Permision> Permisions { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Prescription> Prescriptions { get; set; }
        public virtual DbSet<PrescriptionMedicine> PrescriptionMedicines { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceTreatment> ServiceTreatments { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Treatment> Treatments { get; set; }
        public virtual DbSet<TypeMedicine> TypeMedicines { get; set; }
        public virtual DbSet<WorkingStatu> WorkingStatus { get; set; }
    }
}
