//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongKhamNhaKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailPermision
    {
        public int DetailPermisionId { get; set; }
        public Nullable<int> PermisionId { get; set; }
        public string acctionCode { get; set; }
    
        public virtual Permision Permision { get; set; }
    }
}
