//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongKhamNhaKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine()
        {
            this.PrescriptionMedicines = new HashSet<PrescriptionMedicine>();
        }
    
        public string MedicineId { get; set; }
        public string nameMedicine { get; set; }
        public System.DateTime expirationDate { get; set; }
        public int quantity { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> price { get; set; }
        public string TypeMedicineId { get; set; }
    
        public virtual TypeMedicine TypeMedicine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionMedicine> PrescriptionMedicines { get; set; }
    }
}
