//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongKhamNhaKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionMedicine
    {
        public int PrescriptionMedicineID { get; set; }
        public string PrescriptionId { get; set; }
        public string MedicineId { get; set; }
        public int quantity { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
