//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongKhamNhaKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public string ReceiptId { get; set; }
        public Nullable<System.DateTime> receiptdate { get; set; }
        public Nullable<decimal> total { get; set; }
        public string note { get; set; }
        public string PatientId { get; set; }
        public string StaffId { get; set; }
        public Nullable<bool> statusReceipt { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
