//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongKhamNhaKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTreatment
    {
        public int ServiceTreatmentId { get; set; }
        public string ServiceId { get; set; }
        public string TreatmentId { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Treatment Treatment { get; set; }
    }
}
