//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongKhamNhaKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Treatment()
        {
            this.ServiceTreatments = new HashSet<ServiceTreatment>();
        }
    
        public string TreatmentId { get; set; }
        public string diagnose { get; set; }
        public string method { get; set; }
        public System.DateTime dayOfTreatment { get; set; }
        public string PatientId { get; set; }
        public string StaffId { get; set; }
    
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceTreatment> ServiceTreatments { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
