//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongKhamNhaKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeMedicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypeMedicine()
        {
            this.Medicines = new HashSet<Medicine>();
        }
    
        public string TypeMedicineId { get; set; }
        public string nameTypeOfMedicine { get; set; }
        public string DrugSuppliersId { get; set; }
    
        public virtual DrugSupplier DrugSupplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicine> Medicines { get; set; }
    }
}
