//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongKhamNhaKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingStatu
    {
        public string WorkingStatusId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<System.DateTime> timeBegin { get; set; }
        public Nullable<System.DateTime> timeEnd { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
